-- Phase 2: Alliance Roller state hardening.
-- No schema change is required here: migration 0041 already defines state.
-- Keep this migration as a successful no-op so environments that have not
-- applied 0043 can advance past the superseded duplicate ALTER safely.
